export enum Role {
  CrmAdministrator = "CRM Administrator",
  SalesRepresentative = "Sales Representative",
  SalesManager = "Sales Manager",
  AccountManager = "Account Manager",
  CustomerSupportAgent = "Customer Support Agent",
  SupportManager = "Support Manager",
  MarketingUser = "Marketing User",
  MarketingManager = "Marketing Manager",
  CustomerSuccessManager = "Customer Success Manager",
  OperationsManager = "Operations Manager",
  ExecutiveDirector = "Executive / Director",
  ReadOnlyUser = "Read-Only User",
  LeadQualifierSdr = "Lead Qualifier / SDR",
  BusinessDevelopmentRepresentative = "Business Development Representative",
  InsideSalesRepresentative = "Inside Sales Representative",
  FieldSalesRepresentative = "Field Sales Representative",
  SalesCoordinator = "Sales Coordinator",
  SalesOperationsAnalyst = "Sales Operations Analyst",
  TicketAgent = "Ticket Agent",
  EscalationSpecialist = "Escalation Specialist",
  TechnicalSupportSpecialist = "Technical Support Specialist",
  ServiceDispatcher = "Service Dispatcher",
  FieldServiceTechnician = "Field Service Technician",
  CampaignManager = "Campaign Manager",
  EmailMarketingSpecialist = "Email Marketing Specialist",
  LeadScoringManager = "Lead Scoring Manager",
  DataAnalyst = "Data Analyst",
  DataSteward = "Data Steward",
  SystemOwner = "System Owner",
  CrmDeveloper = "CRM Developer",
  IntegrationSpecialist = "Integration Specialist",
  SecurityAdministrator = "Security Administrator",
  WorkflowAutomationSpecialist = "Workflow Automation Specialist",
  PartnerUser = "Partner User",
  VendorUser = "Vendor User",
  ClientPortalUser = "Client Portal User",
  Auditor = "Auditor",
}

export const CRM_ROLES: readonly Role[] = Object.values(Role);

export const RoleGroup = {
  SystemAdministration: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.SecurityAdministrator,
    Role.CrmDeveloper,
    Role.IntegrationSpecialist,
    Role.WorkflowAutomationSpecialist,
    Role.OperationsManager,
  ],
  UserManagement: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.SecurityAdministrator,
    Role.OperationsManager,
  ],
  UserRead: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.SecurityAdministrator,
    Role.OperationsManager,
    Role.SalesManager,
    Role.SupportManager,
    Role.MarketingManager,
    Role.CustomerSuccessManager,
    Role.ExecutiveDirector,
    Role.DataAnalyst,
    Role.DataSteward,
    Role.Auditor,
    Role.ReadOnlyUser,
  ],
  ProductRead: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.OperationsManager,
    Role.SalesRepresentative,
    Role.SalesManager,
    Role.AccountManager,
    Role.LeadQualifierSdr,
    Role.BusinessDevelopmentRepresentative,
    Role.InsideSalesRepresentative,
    Role.FieldSalesRepresentative,
    Role.SalesCoordinator,
    Role.SalesOperationsAnalyst,
    Role.CustomerSupportAgent,
    Role.SupportManager,
    Role.MarketingUser,
    Role.MarketingManager,
    Role.CustomerSuccessManager,
    Role.ExecutiveDirector,
    Role.DataAnalyst,
    Role.ReadOnlyUser,
    Role.PartnerUser,
    Role.VendorUser,
    Role.ClientPortalUser,
  ],
  ProductWrite: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.OperationsManager,
    Role.SalesOperationsAnalyst,
    Role.SalesCoordinator,
    Role.VendorUser,
  ],
  OrderCreate: [
    Role.CrmAdministrator,
    Role.SalesRepresentative,
    Role.SalesManager,
    Role.AccountManager,
    Role.LeadQualifierSdr,
    Role.BusinessDevelopmentRepresentative,
    Role.InsideSalesRepresentative,
    Role.FieldSalesRepresentative,
    Role.SalesCoordinator,
    Role.PartnerUser,
    Role.ClientPortalUser,
  ],
  OrderRead: [
    Role.CrmAdministrator,
    Role.SystemOwner,
    Role.OperationsManager,
    Role.SalesRepresentative,
    Role.SalesManager,
    Role.AccountManager,
    Role.LeadQualifierSdr,
    Role.BusinessDevelopmentRepresentative,
    Role.InsideSalesRepresentative,
    Role.FieldSalesRepresentative,
    Role.SalesCoordinator,
    Role.SalesOperationsAnalyst,
    Role.CustomerSupportAgent,
    Role.SupportManager,
    Role.TicketAgent,
    Role.EscalationSpecialist,
    Role.CustomerSuccessManager,
    Role.ExecutiveDirector,
    Role.DataAnalyst,
    Role.Auditor,
    Role.ReadOnlyUser,
    Role.PartnerUser,
    Role.ClientPortalUser,
  ],
} as const satisfies Record<string, readonly Role[]>;

export function isRole(value: unknown): value is Role {
  return typeof value === "string" && CRM_ROLES.includes(value as Role);
}
